name: Linting

on: 
  push:
    branches: [ "master" ]
    paths:
      - '**.py'
  pull_request:
    paths:
      - '**.py'

jobs:
  Pylint-Linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12", "3.11"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4.7.1
      with:
        python-version: ${{ matrix.python-version }}
        allow-prereleases: true
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
    - name: Analysing the code with pylint
      run: |
        find . -name '*.py' -exec pylint --disable=E0401 {} \;

  Pylint-Windows:
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: ["3.12", "3.11"]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4.7.1
        with:
          python-version: ${{ matrix.python-version }}
          allow-prereleases: true
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint
      - name: Analyzing the code with pylint
        run: |
          Get-ChildItem -Recurse -Filter '*.py' | ForEach-Object { pylint --disable=E0401 $_.FullName --exit-zero }

  Ruff:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
    steps:
      - uses: actions/checkout@v4
      - uses: chartboost/ruff-action@v1.0.0
        with:
          args: . --exit-zero --ignore E501
        name: Lint with Ruff on ${{ matrix.os }}
